[package]
name = "tenken"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tenken"
path = "src/main.rs"

[dependencies]
actix-web = "4.0.0-beta.20"
actix = "0.11.0-beta.2"
regex = "1"
fxhash = "0.2.1"
thiserror = "1.0"
evmap = "4.1.0"
lazy_static = "1.4.0"
stopwatch = "0.0.7"
